name: PolarWorlds
version: 1.0.7
main: net.jirmjahu.polarworlds.PolarWorlds
author: jirmjahu
api-version: '1.20'
commands:
  world:
    description:
    permission: polarworlds.command.world
    aliases:
      - pw
      - polarworlds